### PR TITLE
Use clang tidy to update codes for readability.

### PR DESCRIPTION
**Pull request by imikejackson**
clang-tidy was run with the following arguments:
-checks='-*,+readability-*,-readability-identifier-naming,modernize-use-equals-default'

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

### CODE REVIEW

**Review by mmarineBlueQuartz — CHANGES_REQUESTED** [review]
Take a look at FindArrayStatistics.cpp starting at lines 486 and 529.  Clang-Tidy shouldn't be changing the functionality of a template.

**Comment by imikejackson** [comment]
I am getting compile errors that don't make any sense for those so I had commented them out wanting to come back and fix them. I obviously forgot to get back to them.


FAILED: Plugins/DREAM3DReview/CMakeFiles/DREAM3DReviewServer.dir/DREAM3DReviewFilters/FindArrayStatistics.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DDEBUG -DDREAM3DReviewServer_EXPORTS -DH5_BUILT_AS_DYNAMIC_LIB=1 -DQT_CORE_LIB -DQT_NETWORK_LIB -IPlugins/DREAM3DReview -I/Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/Plugins/DREAM3DReview -IPlugins/DREAM3DReview/DREAM3DReviewServer_autogen/include -I/Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/Plugins -IPlugins -IPlugins/DREAM3DReview/DREAM3DReviewFilters -I/Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/SIMPL/Source -ISIMPLView/SIMPL -I/Users/Shared/DREAM3D_SDK/Eigen-3.3.5/include/eigen3 -ISIMPLView/SIMPL/SIMPLib/Common -ISIMPLView/SIMPL/SIMPLib/DataArrays -ISIMPLView/SIMPL/SIMPLib/DataContainers -ISIMPLView/SIMPL/SIMPLib/Geometry -ISIMPLView/SIMPL/SIMPLib/HDF5 -ISIMPLView/SIMPL/SIMPLib/Math -ISIMPLView/SIMPL/SIMPLib/StatsData -ISIMPLView/SIMPL/SIMPLib/Utilities -ISIMPLView/SIMPL/SIMPLib/ITK -ISIMPLView/SIMPL/SIMPLib/Filtering -ISIMPLView/SIMPL/SIMPLib/FilterParameters -ISIMPLView/SIMPL/SIMPLib/VTKUtils -ISIMPLView/SIMPL/SIMPLib/Plugin -ISIMPLView/SIMPL/SIMPLib/CoreFilters -ISIMPLView/SIMPL/SIMPLib/TestFilters -I. -I/Users/mjackson/DREAM3D-Dev/DREAM3D/Source -iframework /Users/Shared/DREAM3D_SDK/Qt5.10.1/5.10.1/clang_64/lib -isystem /Users/Shared/DREAM3D_SDK/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers -isystem /Users/Shared/DREAM3D_SDK/Qt5.10.1/5.10.1/clang_64/./mkspecs/macx-clang -isystem /Users/Shared/DREAM3D_SDK/hdf5-1.8.20-Debug/include -isystem /Users/Shared/DREAM3D_SDK/Qt5.10.1/5.10.1/clang_64/lib/QtNetwork.framework/Headers -isystem /Users/Shared/DREAM3D_SDK/tbb2018_20180618oss/tbb2018_20180618oss/include -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -mfpmath=sse -Wno-inconsistent-missing-override -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.10 -fPIC   -fPIC -std=c++11 -MD -MT Plugins/DREAM3DReview/CMakeFiles/DREAM3DReviewServer.dir/DREAM3DReviewFilters/FindArrayStatistics.cpp.o -MF Plugins/DREAM3DReview/CMakeFiles/DREAM3DReviewServer.dir/DREAM3DReviewFilters/FindArrayStatistics.cpp.o.d -o Plugins/DREAM3DReview/CMakeFiles/DREAM3DReviewServer.dir/DREAM3DReviewFilters/FindArrayStatistics.cpp.o -c /Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/Plugins/DREAM3DReview/DREAM3DReviewFilters/FindArrayStatistics.cpp
/Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/Plugins/DREAM3DReview/DREAM3DReviewFilters/FindArrayStatistics.cpp:488:7: error: no function template matches function template specialization 'standardizeDataByIndex'
 void standardizeDataByIndex<bool>(IDataArray::Pointer dataPtr, FloatArrayType::Pointer standardized, bool useMask, bool* mask, int32_t* featureIds, IDataArray::Pointer meanPtr,
      ^
/Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/Plugins/DREAM3DReview/DREAM3DReviewFilters/FindArrayStatistics.cpp:454:6: note: candidate template ignored: could not match 'void (IDataArray::Pointer, FloatArrayType::Pointer, bool, const bool *, const int32_t *, IDataArray::Pointer, IDataArray::Pointer)' (aka 'void (shared_ptr<IDataArray>, shared_ptr<DataArray<float> >, bool, const bool *, const int *, shared_ptr<IDataArray>, shared_ptr<IDataArray>)') against 'void (IDataArray::Pointer, FloatArrayType::Pointer, bool, bool *, int32_t *, IDataArray::Pointer, IDataArray::Pointer)' (aka 'void (shared_ptr<IDataArray>, shared_ptr<DataArray<float> >, bool, bool *, int *, shared_ptr<IDataArray>, shared_ptr<IDataArray>)')
void standardizeDataByIndex(IDataArray::Pointer dataPtr, FloatArrayType::Pointer standardized, bool useMask, const bool* mask, const int32_t* featureIds, IDataArray::Pointer meanPtr,
     ^
/Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/Plugins/DREAM3DReview/DREAM3DReviewFilters/FindArrayStatistics.cpp:529:19: error: no function template matches function template specialization 'standardizeData'
 template <> void standardizeData<bool>(IDataArray::Pointer dataPtr, FloatArrayType::Pointer standardized, bool useMask, bool* mask, IDataArray::Pointer meanPtr, IDataArray::Pointer stdPtr)
                  ^
/Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/Plugins/DREAM3DReview/DREAM3DReviewFilters/FindArrayStatistics.cpp:497:28: note: candidate template ignored: could not match 'void (IDataArray::Pointer, FloatArrayType::Pointer, bool, const bool *, IDataArray::Pointer, IDataArray::Pointer)' (aka 'void (shared_ptr<IDataArray>, shared_ptr<DataArray<float> >, bool, const bool *, shared_ptr<IDataArray>, shared_ptr<IDataArray>)') against 'void (IDataArray::Pointer, FloatArrayType::Pointer, bool, bool *, IDataArray::Pointer, IDataArray::Pointer)' (aka 'void (shared_ptr<IDataArray>, shared_ptr<DataArray<float> >, bool, bool *, shared_ptr<IDataArray>, shared_ptr<IDataArray>)')
template <typename T> void standardizeData(IDataArray::Pointer dataPtr, FloatArrayType::Pointer standardized, bool useMask, const bool* mask, IDataArray::Pointer meanPtr, IDataArray::Pointer stdPtr)
                           ^

**Comment by imikejackson** [comment]
@mmarineBlueQuartz  I started out with a fresh run of Clang-Tidy and removed some of the checks this time. New commits are pushed up.

**Review by mmarineBlueQuartz — APPROVED** [review]
This looks good.

**Pull request merged**
