### PR TITLE
New ComputeFeatureEigenstrains Filter and FFTHDFWriterFilter Addition

### PR DESCRIPTION
**Pull request by cartercocke**
Hello!

Here is the current state of our "Compute Eigenstrains by Feature (Grain/Inclusion)" filter. There are also changes to the FFTHDFWriterFilter to optionally output the calculated eigenstrains as an HDF file for MASSIF. There are a few things and issues I want to immediately highlight below:

- The code has only been compiled/tested on Windows 10
- The ComputeFeatureEigenstrains filter is complete and is working. I could not get boost working, so on line 555 in ComputeFeatureEigenstrains.cpp I had to use my own implementation of gauss integration (the boost implementation is commented out). The documentation is complete.
- The FFTHDFWriterFilter changes are working, but I'm not sure the changes are made in the most robust way. Also, as I am writing this, I realized I did not update the documentation for this filter.
- The ComputeFeatureEigenstrainsTest is incomplete, and no example pipelines are given (these will both require some external data)
- No python examples (also Python interface not tested)
- Looks like some lines are incorrectly changed in some of the cmake files.

Let me know what steps I should take next!

Carter

### CODE REVIEW

**Comment by imikejackson** [comment]
Thanks for the PR. A few questions:

Can the filter be run on something like the small IN100 or do we need a specific FFT data set?

**Comment by cartercocke** [comment]
@imikejackson
This filter is dependent on outputs from the FindShapes filter, so it inherently requires a 3D dataset with image/voxel data, although the filter itself only reads/writes feature data. To your question: I don't think the IN100 dataset will work unless it is modified. I have access to two (big) real datasets that I have been using for my testing, but I do not have permission to redistribute them. I'm not sure if synthetic data is frowned upon for example pipelines/testing, but I could generate a synthetic microstructure (something like 32x32x32 voxels?) and then manually add the required (elastic strain) feature data using randomly generated values. Would that work? Otherwise, I can look into getting permission to use one of those real datasets (as a low-resolution/cropped version with small file size). Thoughts on these options?

**Comment by imikejackson** [comment]
@cartercocke can you give @imikejackson  and @JDuffeyBQ write access to your fork. We have some changes that we would like to push.

**Comment by cartercocke** [comment]
@imikejackson "Allow edits by maintainers" is already enabled, so I also just invited you both individually to the forked repo in case that doesn't work

**Comment by imikejackson** [comment]
You can check on build progress at this link

https://github.com/BlueQuartzSoftware/DREAM3DCI/pull/59

**Comment by imikejackson** [comment]
The synthetic could work, I just like the idea of having random anything in the tests. We have some issues with another unit test randomly failing because randomly fall outside of a range. if the data set was small enough a few MB in size we could just place it in the Data directory and use that. So a pre built synthetic of 32^3 that has the necessary data would actually be about the right size for this test.

**Comment by cartercocke** [comment]
That sounds good, I will create a small dataset that is synthetic but still deterministic for testing purposes. Can the correct output simply be stored as a .dream3d file and loaded into the unit test for comparison?

**Comment by cartercocke** [comment]
So I made a small synthetic test dataset but I ran into an issue with some grains giving nan results. This happened when two semi-axis lengths were exactly equal, but I added two limiting case solutions that fix this. Also, it seems like there may possibly be a bug in the FindShapes filter where for some grains the last angle in AxisEulerAngles is NaN. Not sure what the cause of this is, though.

**Comment by imikejackson** [comment]
@cartercocke Thank you for the data. can you add a pipeline file that sets up the pipeline for testing?

**Comment by cartercocke** [comment]
@imikejackson just added the synthetic dataset and an example pipeline. The pipeline file locations are for my local machine, so those will need to be changed.

**Comment by cartercocke** [comment]
@imikejackson It would be good to add unit tests for the gauss_integration and find_eshelby functions. I tried to get add the (unnamed) namespace into the header file so the functions could be used in the test file, but I'm not very proficient with C++ and I could not figure out how to do so. Would it be possible for you to set up that namespace in the header file so I can begin writing tests for those functions?

**Comment by JDuffeyBQ** [comment]
@cartercocke I moved `gauss_integration` and `find_eshelby` to the `util/EigenstrainsHelper.hpp` file so you can include that in your unit test. I also re-based the branch onto our current develop so there won't be compile issues with the latest updates for the rest of our repositories.

**Comment by cartercocke** [comment]
Thank you @JDuffeyBQ!

**Comment by cartercocke** [comment]
I added a bunch of unit tests for both the filter itself and for the two helper functions. I did not add (commented out) tests to test changing the array paths, but other than that I believe the unit test is pretty complete at this point.

Also, I think there is an issue somewhere around line 709 in ```FindShapes.cpp``` where the uberelim array sometimes has a nan value, thus leading to a nan rotation matrix row and one nan axis euler angle. This nan value occurs for two features in the test pipeline/dataset I added in this PR, so I added some temporary code in the test that skips the nan values. Should I create a new issue for this on the main dream3d repo?

**Comment by JDuffeyBQ** [comment]
@cartercocke I think that would be good so we can start tracking it independently of this PR.

**Comment by imikejackson** [comment]
@cartercocke Line 235 in your unit test aborts because the code walked off the end of the array. Could you double check your unit test code?

**Comment by cartercocke** [comment]
@imikejackson Fixed. It was a stupid for loop copy paste mistake... I'm not sure how that even ran on my machine! The unit test outputs "Error Closing HDF5 File. -1" twice after the example pipeline is fully run, but when the pipeline is run in the gui this is not output. I'm assuming that since this is output twice it is an issue with the FFTHDFWriterFilter changes, but I'm not sure why this is only output in the unit test pipeline call. I will look into this though

**Comment by cartercocke** [comment]
I updated the FFTHDFWriterFilter to mirror the DataContainerWriter filter closing method which fixes the "Error Closing HDF5 File. -1" issue.

**Comment by cartercocke** [comment]
@imikejackson I think the filter changes are mostly complete at this point. Is there anything else I should/can do?

**Comment by imikejackson** [comment]
@JDuffeyBQ and I will make a final review this week. Hopefully.

**Comment by imikejackson** [comment]
This wasn't supposed to be closed... .

**Comment by imikejackson** [comment]
@cartercocke I pushed a new branch "feature/eigen_strains" to your fork. Can you put in a new PR for that branch?

**Pull request closed without merging**
